package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 19 12:50:15 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PAYROLL_LINES_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PAYROLL_LINES_VOImpl() {
    }
}

