package model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 12 21:22:19 IST 2020
// ---------------------------------------------------------------------
public interface Naresco_AM extends ApplicationModule {
    String callingReportPkg(String buid, String date);
}

